"""C source from loop IR, and a gcc driver with a content-addressed cache.

Every kernel becomes one exported function with a single calling convention:

    int32_t nc_k7(void **p, const int64_t *s);

``p[0]`` is the output, ``p[1..]`` the operands (already offset to their
view's first element), ``s`` the symbol values. A non-zero return is a kernel
reporting bad input, which the runtime turns into an exception.

The emitted C is deterministic: the same program renders the same bytes,
which is both a phase 2 gate and what makes the cache work. The library is
named by a hash of its source, the compiler's version and its flags, so an
unchanged program never reaches gcc twice.

The flags are chosen so the C computes what the graph says and nothing
looser. ``-ffp-contract=off`` stops gcc fusing a multiply and an add into an
FMA, which rounds once instead of twice. There is no ``-ffast-math``, so no
reduction is reassociated, and the matmul and sum loops add in index order.
``-fwrapv`` defines signed overflow as wrapping, which is what NumPy's int8
arithmetic does.
"""

from __future__ import annotations

import hashlib
import os
import platform
import shutil
import subprocess
import sys
import tempfile
from functools import lru_cache
from pathlib import Path

import numpy as np

from nanocompile import dtypes
from nanocompile import loopir as L

C_TYPES = {
    dtypes.f32: "float",
    dtypes.i64: "int64_t",
    dtypes.i32: "int32_t",
    dtypes.i8: "int8_t",
    dtypes.bool_: "uint8_t",
}

CFLAGS = ("-O3", "-march=native", "-ffp-contract=off", "-fwrapv", "-fno-math-errno")

_BINARY_C = {"add": "+", "sub": "-", "mul": "*", "div": "/", "le": "<=", "lt": "<", "ne": "!=", "or": "||"}
_PRECEDENCE = {"or": 0, "le": 1, "lt": 1, "ne": 1, "add": 2, "sub": 2, "mul": 3, "div": 3}
_UNARY_C = {"exp": "expf", "sqrt": "sqrtf", "sin": "sinf", "cos": "cosf"}

PRELUDE = """\
/* Generated by nanocompile. One function per distinct kernel. */
#include <stdint.h>
#include <math.h>

#ifdef _WIN32
#define NC_EXPORT __declspec(dllexport)
#else
#define NC_EXPORT __attribute__((visibility("default")))
#endif
"""


class CompileError(RuntimeError):
    """gcc rejected generated code. Always a bug in the code generator."""


def _float_literal(value: float) -> str:
    value = float(np.float32(value))
    if np.isnan(value):
        return "NAN"
    if np.isinf(value):
        return "INFINITY" if value > 0 else "(-INFINITY)"
    if value == 0.0:
        return "-0.0f" if np.signbit(value) else "0.0f"
    # Hex floats are exact: the literal is the float32 the graph holds.
    return f"{value.hex()}f"


def _const(c: L.Const) -> str:
    if c.dtype.is_float:
        return _float_literal(c.value)
    value = int(c.value)
    return f"INT64_C({value})" if abs(value) >= 2**31 else str(value)


def render_scalar(x: L.Scalar, parent: int = -1, right: bool = False) -> str:
    if isinstance(x, L.Const):
        return _const(x)
    if isinstance(x, L.Var):
        return x.name
    if isinstance(x, L.Sym):
        return f"s[{x.index}]"
    if isinstance(x, L.Load):
        return f"x{x.param}[{render_scalar(x.index)}]"
    if isinstance(x, L.Cast):
        return f"({C_TYPES[x.dtype]})({render_scalar(x.a)})"
    if isinstance(x, L.Select):
        return f"({render_scalar(x.cond)} ? {render_scalar(x.a)} : {render_scalar(x.b)})"
    if isinstance(x, L.Unary):
        a = render_scalar(x.a)
        if x.op == "neg":
            return f"(-{a})"
        if x.op == "reciprocal":
            return f"(1.0f / {a})"
        return f"{_UNARY_C[x.op]}({a})"
    if isinstance(x, L.Binary):
        mine = _PRECEDENCE[x.op]
        text = f"{render_scalar(x.a, mine)} {_BINARY_C[x.op]} {render_scalar(x.b, mine, right=True)}"
        # Parenthesize when the parent binds tighter, or on the right of a
        # non-associative operator at the same level: a - (b + c).
        if mine < parent or (right and mine == parent):
            return f"({text})"
        return text
    raise TypeError(f"cannot render {x!r}")


def _render_stmts(stmts: tuple[L.Stmt, ...], depth: int) -> list[str]:
    pad = "    " * depth
    lines: list[str] = []
    for stmt in stmts:
        if isinstance(stmt, L.Loop):
            lines.append(
                f"{pad}for (int64_t {stmt.var} = 0; {stmt.var} < {render_scalar(stmt.extent)}; ++{stmt.var}) {{"
            )
            lines.extend(_render_stmts(stmt.body, depth + 1))
            lines.append(f"{pad}}}")
        elif isinstance(stmt, L.Store):
            lines.append(f"{pad}x0[{render_scalar(stmt.index)}] = {render_scalar(stmt.value)};")
        elif isinstance(stmt, L.Let):
            ctype = C_TYPES[stmt.value.dtype]
            lines.append(f"{pad}{ctype} {stmt.var} = {render_scalar(stmt.value)};")
        elif isinstance(stmt, L.Assign):
            lines.append(f"{pad}{stmt.var} = {render_scalar(stmt.value)};")
        elif isinstance(stmt, L.Fail):
            lines.append(f"{pad}if ({render_scalar(stmt.cond)}) return {stmt.code};")
        else:
            raise TypeError(f"cannot render {stmt!r}")
    return lines


def render_kernel(kernel: L.Kernel, name: str) -> str:
    lines = [f"/* {kernel.primitive} */", f"NC_EXPORT int32_t {name}(void **p, const int64_t *s) {{"]
    for i, param in enumerate(kernel.params):
        ctype = C_TYPES[param.dtype]
        qualifier = "" if param.writable else "const "
        lines.append(f"    {qualifier}{ctype} *restrict x{i} = ({qualifier}{ctype} *)p[{i}];")
    lines.extend(_render_stmts(kernel.body, 1))
    lines.append("    (void)s;")
    lines.append("    return 0;")
    lines.append("}")
    return "\n".join(lines)


def kernel_name(index: int) -> str:
    return f"nc_k{index}"


def render_library(kernels: list[L.Kernel]) -> str:
    parts = [PRELUDE]
    for index, kernel in enumerate(kernels):
        parts.append(render_kernel(kernel, kernel_name(index)))
    return "\n\n".join(parts) + "\n"


# -- compiling ---------------------------------------------------------------


def compiler() -> str:
    cc = os.environ.get("CC") or shutil.which("gcc")
    if cc is None:
        raise CompileError("no C compiler: put gcc on PATH or set CC")
    return cc


@lru_cache(maxsize=None)
def _compiler_identity(cc: str) -> str:
    """What the cache key needs to know about the toolchain and the machine.

    ``-march=native`` means the same source compiles to different code on a
    different CPU, so the CPU is part of the key alongside the compiler.
    """
    version = subprocess.run([cc, "--version"], capture_output=True, text=True).stdout
    return f"{version.splitlines()[0] if version else cc}|{platform.machine()}|{platform.processor()}"


def cache_dir() -> Path:
    configured = os.environ.get("NANOCOMPILE_CACHE")
    path = Path(configured) if configured else Path.home() / ".cache" / "nanocompile"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _library_suffix() -> str:
    return {"win32": ".dll", "darwin": ".dylib"}.get(sys.platform, ".so")


def library_key(source: str) -> str:
    cc = compiler()
    material = "\n".join([source, " ".join(CFLAGS), _compiler_identity(cc)])
    return hashlib.sha256(material.encode("utf-8")).hexdigest()[:20]


def build_library(source: str) -> tuple[Path, bool]:
    """Compile ``source`` to a shared library, or find it in the cache.

    Returns the library path and whether it was already cached. The library is
    written under a temporary name and renamed into place, so a crash mid-
    compile never leaves a truncated library where the cache will find it.
    """
    cc = compiler()
    path = cache_dir() / f"nc_{library_key(source)}{_library_suffix()}"
    if path.exists():
        return path, True

    with tempfile.TemporaryDirectory(dir=cache_dir()) as scratch:
        src = Path(scratch) / "kernels.c"
        src.write_text(source, encoding="utf-8")
        out = Path(scratch) / path.name
        # -static-libgcc on Windows so the DLL depends on nothing outside the
        # OS; -fPIC elsewhere because a shared object requires it.
        platform_flags = ["-static-libgcc"] if sys.platform == "win32" else ["-fPIC"]
        command = [cc, *CFLAGS, *platform_flags, "-shared", "-o", str(out), str(src)]
        result = subprocess.run(command, capture_output=True, text=True)
        if result.returncode != 0:
            raise CompileError(f"gcc failed:\n{result.stderr[-4000:]}")
        try:
            os.replace(out, path)
        except PermissionError:
            # Another process got there first and has it loaded (Windows locks
            # loaded DLLs). Same key, same source: theirs is ours.
            if not path.exists():
                raise
    return path, False
